### ISSUE TITLE
Do not complain about previously uncached functions

### ISSUE THREAD

**Issue by renatonascalves** [alleyinteractive/Alley-Coding-Standards#32]
### Description

Since WordPress 6.1, certain WordPress uncached functions are cached now, ex.: `get_page_by_path`. VIP ruleset has suggestions for their versions, ex.: `wpcom_vip_get_page_by_path`, for those uncached functions which are cached.

Based on their documentation, it is not required to use their version anymore. There is no benefit or gains.

See: https://docs.wpvip.com/technical-references/caching/uncached-functions/

Let's find a way to remove those suggestions if the minimum supported WordPress version is 6.1:

```xml
<config name="minimum_supported_wp_version" value="6.1" />
```

### Use Case

A project where the minimum supported version is 6.1+.

**Comment by renatonascalves** [comment]
Related: https://github.com/Automattic/VIP-Coding-Standards/issues/720

**Comment by srtfisher** [comment]
With https://github.com/Automattic/VIP-Coding-Standards/issues/720 merged now we can safely use `term_exists()` again without it being flagged as an error.
