### ISSUE TITLE
Check for undefined and unused variables

### ISSUE THREAD

**Issue by renatonascalves** [alleyinteractive/Alley-Coding-Standards#33]
### Description

As titled!

Maybe use https://github.com/sirbrillig/phpcs-variable-analysis or find out why this is not set by WordPress or VIP rulesets.

### Use Case

All!

**Comment by srtfisher** [comment]
This is forthcoming in WPCS 3.0: https://github.com/alleyinteractive/alley-coding-standards/wiki/Upgrading-to-2.0#genericcodeanalysisunusedfunctionparameterfoundgenericcodeanalysisunusedfunctionparameterfoundafterlastused

**Comment by renatonascalves** [comment]
@srtfisher It looks like that only accounts for functions, not undefined or unused variables. 🤔

**Comment by renatonascalves** [comment]
I confirmed this is indeed working but with one caveat.

Because of this VIP rule: 

https://github.com/Automattic/VIP-Coding-Standards/blob/9749b01f4433821bbe46c944b32565e5b07002c0/WordPressVIPMinimum/ruleset.xml#L185-L187

```php
public function format_args( $args ): array {
	$formatted_args = [
		'from' => $args['per_page'] * ( $args['page'] - 1 ),
		'size' => $args['per_page'] ?? 10,
		'sort' => $this->parse_orderby( $args ),
	];

	$cool = ''; // unused variable.

... cut for brevity
```

The ruleset doesn't complain about this `$cool` variable because of those rules. But if I try to actually use it, it will say it is undefined.

```php
public function format_args( $args ): array {
	$formatted_args = $renato; // This works.

... cut for brevity
```
