### ISSUE TITLE
Fix Prefer short array syntax

### ISSUE THREAD

**Issue by renatonascalves** [alleyinteractive/Alley-Coding-Standards#36]
### Description

We are setting this here but it looks like it is not enough in version 2.0.

https://github.com/alleyinteractive/alley-coding-standards/blob/0c57c43173c57f962632928bebbe2da274e3c477/Alley-Interactive/ruleset.xml#L38-L39

This rule alone doesn't work. Or
```
<rule ref="Universal.Arrays.DisallowShortArraySyntax" />

or together
<rule ref="Generic.Arrays.DisallowLongArraySyntax" />
```

I was able to fix like that:

```
<rule ref="WordPress">
    <exclude name="Generic.Arrays.DisallowShortArraySyntax"/>
    <exclude name="Universal.Arrays.DisallowShortArraySyntax"/>
</rule>
```

Related: https://github.com/WordPress/WordPress-Coding-Standards/issues/1968

Goal: Confirm what changed in WordPress and fix it here.

### Use Case

Project using https://github.com/alleyinteractive/alley-coding-standards/releases/tag/v2.0.0

**Comment by GaryJones** [comment]
https://github.com/WordPress/WordPress-Coding-Standards/pull/1920 is the key change for WordPressCS 3.0.
